{{- range $i, $n := (until (int .Values.replicaCount)) -}}
{{- if ne $i 0 }}
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: cluster-{{ $i }}-{{ include "helm-ipfs-cluster.name" $ }}
  labels:
    {{- include "helm-ipfs-cluster.selectorLabels" $ | nindent 4 }}
    nodeType: cluster
  annotations:
    {{- toYaml $.Values.cluster.service.annotations | nindent 4 }}
spec:
  type: {{ $.Values.cluster.service.type | default $.Values.service.type }}
  ports:
  {{- range $.Values.cluster.service.ports }}
  - port: {{ .port }}
    targetPort: {{ .targetPort }}
    name: {{ .name }}
  {{- end }}
  selector:
    {{- include "helm-ipfs-cluster.selectorLabels" $ | nindent 4 }}
    nodeType: cluster
{{- end }}
