apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-ipfs-cluster.ipfs-name" . }}
  labels:
    {{- include "helm-ipfs-cluster.selectorLabels" . | nindent 4 }}
    nodeType: ipfs
  annotations:
    {{- toYaml $.Values.ipfs.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.ipfs.service.type | default .Values.service.type }}
  ports:
  - port: 4001
    name: swarm
  - port: 4002
    name: swarm-udp
  - port: 5001
    name: api
  - port: 8081
    name: ws
  - port: 8080
    name: gateway
  selector:
    {{- include "helm-ipfs-cluster.selectorLabels" . | nindent 4 }}
    nodeType: ipfs
