{{- if gt (len .Values.ipfs.announceAddresses) 0 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ipfs-init-config
data:
  ipfs-config.sh: |-
    ipfs config --json Addresses.AppendAnnounce '{{ toJson .Values.ipfs.announceAddresses }}'
{{- end }}