apiVersion: v1
kind: ConfigMap
metadata:
  name: ipfs-init-config
data:
  001-set-announce.sh: |-
    #!/bin/sh
    set -e
    echo "Setting Announce addresses..."
    ipfs config Addresses.Announce --json '{{ toJson .Values.ipfs.announceAddresses }}'
