{{- if gt (len .Values.ipfs.announceAddressesPerNode) 0 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ipfs-init-config
data:
  ipfs-config.sh: |-
    #!/bin/sh
    ipfs config --json Addresses.AppendAnnounce "[${ANNOUNCE_ADDRESSES}]"
{{- end }}